src/Czechia/Mews.Fiscalizations.Czechia.Tests/IntegrationTests/Basics.cs
src/Czechia/Mews.Fiscalizations.Czechia.Tests/Mews.Fiscalizations.Czechia.Tests.csproj
src/Czechia/Mews.Fiscalizations.Czechia.Tests/UnitTests/CurrencyValueTests.cs
src/Czechia/Mews.Fiscalizations.Czechia.Tests/UnitTests/InputTests.cs
src/Czechia/Mews.Fiscalizations.Czechia/Communication/SoapSigner.cs
src/Czechia/Mews.Fiscalizations.Czechia/Mews.Fiscalizations.Czechia.csproj

CZ fiscalization tests never actually got executed/triggered, that's why we never knew about the issue, so i migrated the tests to use NUnit and fixed the issue with signing the xml.

Migrated Czech fiscalization tests to NUnit and fixed an issue with creating a the signedXML

---

src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
src/Hungary/Mews.Fiscalizations.Hungary/RequestMapper.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Added Invoice lines missing data

---

README.md

Improved the repository readme

---

src/Germany/README.md

Improved the German fiscalization readme

---

README.md
src/Germany/README.md
src/Hungary/README.md

Improved HU fiscalization readme.

---

src/Spain/README.md

Improved Spanish fiscalization readme.

---

.github/workflows/publish-italy.yml

Fixed publishing the Italian fiscalization.

Fixed publishing the italian fiscalization

---

CONTRIBUTING.md

We're gonna have a file for new contributors to know how to effectively extend this repository. It was recommended to us by github in the Insights tab

Introduced CONTRIBUTING.md

---

src/Germany/Mews.Fiscalizations.Germany/V2/Client.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Dto/AuthorizationTokenRequest.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Dto/AuthorizationTokenResponse.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Dto/ClientResponse.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Dto/CreateClientRequest.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Dto/CreateTssRequest.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Dto/FinishTransactionRequest.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Dto/FiskalyErrorResponse.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Dto/TransactionRequest.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Dto/TransactionResponse.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Dto/TssResponse.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Dto/UpdateTssRequest.cs
src/Germany/Mews.Fiscalizations.Germany/V2/FiskalyClient.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/AccessToken.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Bill.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Client.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Item.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Payment.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Result/ErrorResult.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Result/FiskalyError.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Result/ResponseResult.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Signature.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Transaction.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/TransactionState.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Tss.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Types/ApiKey.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Types/ApiSecret.cs
src/Germany/Mews.Fiscalizations.Germany/V2/ModelMapper.cs
src/Germany/Mews.Fiscalizations.Germany/V2/RequestCreator.cs

Copy pasted v1 code into v2 folder

---

src/Germany/Mews.Fiscalizations.Germany.Tests/V1/ClientTests.cs
src/Germany/Mews.Fiscalizations.Germany.Tests/V1/TestFixture.cs
src/Germany/Mews.Fiscalizations.Germany.Tests/V1/TransactionTests.cs
src/Germany/Mews.Fiscalizations.Germany.Tests/V1/TssTests.cs
src/Germany/Mews.Fiscalizations.Germany.Tests/V2/ClientTests.cs
src/Germany/Mews.Fiscalizations.Germany.Tests/V2/TestFixture.cs
src/Germany/Mews.Fiscalizations.Germany.Tests/V2/TransactionTests.cs
src/Germany/Mews.Fiscalizations.Germany.Tests/V2/TssTests.cs

Introduced V1 and V2 folders for tests.
Fixes #issue

Introduced V1 and V2 folders for tests

---

src/Spain/Mews.Fiscalizations.Spain.Tests/Basics.cs
src/Spain/Mews.Fiscalizations.Spain/Client.cs
src/Spain/Mews.Fiscalizations.Spain/Communication/SoapClient.cs
src/Spain/Mews.Fiscalizations.Spain/Dto/Responses/SoapFaultResponse.cs
src/Spain/Mews.Fiscalizations.Spain/Model/Response/ErrorResult.cs
src/Spain/Mews.Fiscalizations.Spain/Model/Response/ResponseResult.cs
src/Spain/Mews.Fiscalizations.Spain/Nif/NifValidator.cs

This this part 1 of PR series which suppose to add handling of soap failures.
In scope: introduce result co-product with minimum changes.
Fixes [RND-80626](https://mews.myjetbrains.com/youtrack/issue/RND-80626)

Introduce soap action error handling, part 1

---

src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj

This this part 4 of PR series which suppose to add handling of soap failures.
In scope: 
- Bump nugget packages version. 
Fixes [RND-80626](https://mews.myjetbrains.com/youtrack/issue/RND-80626)

Introduce soap action error handling, part 4

---

src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain/AssemblyInfo.cs
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj
src/Spain/README.md

- Removing exposure of internals of Spain fiscalization to tests
- Spain fiscalization documentation update.
Fixes #issue

Introduce soap action error handling, part 6

---

src/Hungary/Mews.Fiscalizations.Hungary/Models/Invoice/Invoice.cs
src/Hungary/Mews.Fiscalizations.Hungary/Models/Types/ExchangeRate.cs

Just improved some code as I'm writing the blog post.
Fixes #issue

Blogpost improvement

---

src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Italy/Mews.Fiscalizations.Italy/Uniwix/Communication/UniwixClient.cs
src/Italy/Mews.Fiscalizations.Italy/Uniwix/Errors/ErrorType.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Handling of Italian fiscal registry error -12.
-12 error code means that the file is already present in the queue.
Fixes #issue

Handling of italian fiscal registry error code "-12"

---

src/Core/Mews.Fiscalizations.Core/Mews.Fiscalizations.Core.csproj
src/Core/Mews.Fiscalizations.Core/Model/Countries/Countries.cs
src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj

Fixed Ireland taxpayer number validation regex.

Fixed Ireland tax payer number validation regex.

---

.github/workflows/build-and-test-all-linux.yml
.github/workflows/build-and-test-all-windows.yml
.github/workflows/build-and-test-austria-linux.yml
.github/workflows/build-and-test-austria-windows.yml
.github/workflows/publish-all.yml
.github/workflows/publish-austria.yml
src/Austria/Mews.Fiscalizations.Austria.Tests/ATrustSignerTests.cs
src/Austria/Mews.Fiscalizations.Austria/Dto/Receipt.cs

Added A-Trust test account and enabled the tests back.

Added A-Trust test account and enabled the tests back.

---

src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain/Converters/ModelToDtoConverter.cs
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj

Improved SII country serialization error logging.
Fixes #issue

Improved SII country serialization error logging

---

src/Core/Mews.Fiscalizations.Core/Validations/ObjectValidations.cs
src/Spain/Mews.Fiscalizations.Spain.Tests/Basics.cs
src/Spain/Mews.Fiscalizations.Spain/Converters/ModelToDtoConverter.cs
src/Spain/Mews.Fiscalizations.Spain/Model/Enums/TaxMode.cs
src/Spain/Mews.Fiscalizations.Spain/Model/Request/Invoice.cs
src/Spain/Mews.Fiscalizations.Spain/Model/Request/SimplifiedInvoice.cs
src/Spain/README.md
src/TicketBai/Mews.Fiscalizations.TicketBai/Environment.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/CauseOfExemption.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/CorrectingInvoiceCode.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/CorrectingInvoiceType.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/IdType.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/IssuerType.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/TaxMode.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/TaxRegulationType.cs

Introduced TicketBai request enums.

Introduced TicketBai request enums

---

src/Austria/Mews.Fiscalizations.Austria.Tests/Mews.Fiscalizations.Austria.Tests.csproj
src/Austria/Mews.Fiscalizations.Austria/Mews.Fiscalizations.Austria.csproj
src/Core/Mews.Fiscalizations.Core.Tests/Mews.Fiscalizations.Core.Tests.csproj
src/Core/Mews.Fiscalizations.Core/Mews.Fiscalizations.Core.csproj
src/Czechia/Mews.Fiscalizations.Czechia.Tests/Mews.Fiscalizations.Czechia.Tests.csproj
src/Czechia/Mews.Fiscalizations.Czechia/Mews.Fiscalizations.Czechia.csproj
src/Germany/Mews.Fiscalizations.Germany.Tests/Mews.Fiscalizations.Germany.Tests.csproj
src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
src/Hungary/Mews.Fiscalizations.Hungary.Tests/Mews.Fiscalizations.Hungary.Tests.csproj
src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
src/Italy/Mews.Fiscalizations.Italy.Tests/Mews.Fiscalizations.Italy.Tests.csproj
src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Mews.Fiscalizations.All.props
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain.Tests/Mews.Fiscalizations.Spain.Tests.csproj
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj
src/TicketBai/Mews.Fiscalizations.TicketBai.Tests/Mews.Fiscalizations.TicketBai.Tests.csproj
src/TicketBai/Mews.Fiscalizations.TicketBai/Mews.Fiscalizations.TicketBai.csproj

Bumped NuGet packages versions.

Bumped NuGet packages versions.

---

src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Software/Developer.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Software/ForeignDeveloper.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Software/LocalDeveloper.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Software/Software.cs

Introduced TicketBai software and developer models.

Introduced TicketBai software and developer models

---

src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Issuer.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/PostalCode.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Receiver/ForeignReceiver.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Receiver/LocalReceiver.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Receiver/Receiver.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Receiver/ReceiverInfo.cs

Introduced TicketBai receiver and issuer models.

Introduced TicketBai receiver and issuer models

---

src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Invoice/InvoiceFooter.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Invoice/OriginalInvoiceInfo.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Invoice/PreviousInvoiceChain.cs

Introduced TicketBai invoice footer and original invoice models

Introduced TicketBai invoice footer and original invoice models

---

src/Core/Mews.Fiscalizations.Core/Validations/ObjectValidations.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Invoice/CorrectedInvoice.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Invoice/CorrectingInvoice.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Invoice/CorrectingInvoiceAmount.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Invoice/Invoice.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Invoice/InvoiceData.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/Invoice/InvoiceHeader.cs

Introduced TicketBai invoice models.

Introduced TicketBai invoice models

---

src/TicketBai/Mews.Fiscalizations.TicketBai/DtoToModelConverter.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/SendInvoiceResponse.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/Model/SendInvoiceValidationResult.cs

Introduced TicketBai send invoice response model.
- [x Feature.

Introduced TicketBai send invoice response model

---

src/TicketBai/Mews.Fiscalizations.TicketBai/ModelToDtoConverter.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/QrCodeUriGenerator.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/ServiceInfo.cs
src/TicketBai/Mews.Fiscalizations.TicketBai/TicketBaiClient.cs

Moved things around and removed useless/duplicate code.
Fixes #issue

Some ticketbai project cleanups

---

src/Basque/Mews.Fiscalizations.Basque.Tests/SendInvoiceTests.cs
src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Basque/Mews.Fiscalizations.Basque/Model/Invoice/InvoiceHeader.cs
src/Basque/Mews.Fiscalizations.Basque/Model/Invoice/InvoiceItem.cs
src/Basque/Mews.Fiscalizations.Basque/ModelToDtoConverter.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Improved Basque fiscalization DTO.
1. Made discount optional
2. Removed duplicate dates.

Improved Basque fiscalization DTO

---

src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
src/Hungary/Mews.Fiscalizations.Hungary/Models/Invoice/ForeignCompany.cs
src/Hungary/Mews.Fiscalizations.Hungary/Models/Invoice/Invoice.cs
src/Hungary/Mews.Fiscalizations.Hungary/Models/Invoice/InvoiceItem.cs
src/Hungary/Mews.Fiscalizations.Hungary/Models/Invoice/InvoiceStatus.cs
src/Hungary/Mews.Fiscalizations.Hungary/Models/Invoice/ItemAmounts.cs
src/Hungary/Mews.Fiscalizations.Hungary/Models/Invoice/SimpleAddress.cs
src/Hungary/Mews.Fiscalizations.Hungary/Models/Invoice/TaxSummaryItem.cs
src/Hungary/Mews.Fiscalizations.Hungary/Models/SoftwareIdentification.cs
src/Hungary/Mews.Fiscalizations.Hungary/Models/TaxPayer/TaxPayerData.cs
src/Hungary/Mews.Fiscalizations.Hungary/RequestCreator.cs
src/Hungary/Mews.Fiscalizations.Hungary/RequestMapper.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Replaced nullable properties with IOption - HU lib

Replaced nullable properties with IOption - HU lib

---

src/Basque/Mews.Fiscalizations.Basque.Tests/SendInvoiceTests.cs
src/Basque/Mews.Fiscalizations.Basque.Tests/TestFixture.cs
src/Basque/Mews.Fiscalizations.Basque/DtoToModelConverter.cs
src/Basque/Mews.Fiscalizations.Basque/Model/ErrorCode.cs
src/Basque/Mews.Fiscalizations.Basque/Model/InvoiceState.cs
src/Basque/Mews.Fiscalizations.Basque/Model/SendInvoiceResponse.cs
src/Basque/Mews.Fiscalizations.Basque/Model/SendInvoiceValidationResult.cs

Added more test cases for the basque fiscal library and improved the error handling.

Added more test cases for the basque fiscal library

---

src/Basque/Mews.Fiscalizations.Basque.Tests/SendInvoiceTests.cs
src/Basque/Mews.Fiscalizations.Basque/DtoToModelConverter.cs
src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Basque/Mews.Fiscalizations.Basque/Model/SendInvoiceResponse.cs
src/Basque/Mews.Fiscalizations.Basque/TicketBaiClient.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Extended Basque lib with chained tests and extended the response with the Signature
The signature will be needed to chain the invoice (the first 100 characters must be provided in the original invoice data)

Extended Basque lib with chained tests and extended the response with the Signature

---

src/Hungary/Mews.Fiscalizations.Hungary.Tests/TestFixture.cs
src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
src/Hungary/Mews.Fiscalizations.Hungary/ModelMapper.cs
src/Hungary/Mews.Fiscalizations.Hungary/Models/Result/ResponseResult.cs
src/Hungary/Mews.Fiscalizations.Hungary/NavClient.cs
src/Hungary/Mews.Fiscalizations.Hungary/Utils/Client.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Extended the HU lib result with the xml request and response.
- [ x ] Consolidation.

Extended the HU lib result with the xml request and response.

---

src/Austria/Mews.Fiscalizations.Austria.Tests/Mews.Fiscalizations.Austria.Tests.csproj
src/Austria/Mews.Fiscalizations.Austria/Mews.Fiscalizations.Austria.csproj
src/Basque/Mews.Fiscalizations.Basque.Tests/Mews.Fiscalizations.Basque.Tests.csproj
src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Basque/Mews.Fiscalizations.Basque/ModelToDtoConverter.cs
src/Core/Mews.Fiscalizations.Core.Tests/Mews.Fiscalizations.Core.Tests.csproj
src/Czechia/Mews.Fiscalizations.Czechia.Tests/Mews.Fiscalizations.Czechia.Tests.csproj
src/Czechia/Mews.Fiscalizations.Czechia/Mews.Fiscalizations.Czechia.csproj
src/Germany/Mews.Fiscalizations.Germany.Tests/Mews.Fiscalizations.Germany.Tests.csproj
src/Hungary/Mews.Fiscalizations.Hungary.Tests/Mews.Fiscalizations.Hungary.Tests.csproj
src/Italy/Mews.Fiscalizations.Italy.Tests/Mews.Fiscalizations.Italy.Tests.csproj
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain.Tests/Mews.Fiscalizations.Spain.Tests.csproj
src/Spain/Mews.Fiscalizations.Spain/Converters/ModelToDtoConverter.cs
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj

TicketBai and SII country list Dtos don't recognize Kosovo country code, so it's will be reported as Serbia.
Fixes #issue

Fixed SII reporting of invoicecs for Kosovo customers

---

src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Basque/Mews.Fiscalizations.Basque/Model/ErrorCode.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Extended Basque fiscalization error codes with InvalidReceiverTaxIdentifier.

Extended Basque fiscalization error codes

---

src/Core/Mews.Fiscalizations.Core.Tests/Model/Legal/TaxpayerIdentificationNumberTests.cs
src/Core/Mews.Fiscalizations.Core/Mews.Fiscalizations.Core.csproj
src/Core/Mews.Fiscalizations.Core/Model/Countries/Countries.cs
src/Spain/Mews.Fiscalizations.Spain.Tests/Basics.cs

Fixed the Spanish tax id validation.

Fixed the Spanish tax id validation.

---

src/Basque/Mews.Fiscalizations.Basque.Tests/InvoiceTestData.cs
src/Basque/Mews.Fiscalizations.Basque.Tests/TestFixture.cs
src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Basque/Mews.Fiscalizations.Basque/Model/Issuer.cs
src/Basque/Mews.Fiscalizations.Basque/Model/Receiver/LocalReceiver.cs
src/Basque/Mews.Fiscalizations.Basque/Model/Receiver/Receiver.cs
src/Czechia/Mews.Fiscalizations.Czechia/Mews.Fiscalizations.Czechia.csproj
src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj

Fixed Basque fiscalization tax id validations.

Fixed Basque fiscalization tax id validations

---

src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Czechia/Mews.Fiscalizations.Czechia/Mews.Fiscalizations.Czechia.csproj
src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj

Bumped the version of fiscal libraries to use latest Core version

Bumped the version of fiscal libraries to use latest Core version

---

src/Core/Mews.Fiscalizations.Core/Mews.Fiscalizations.Core.csproj
src/Core/Mews.Fiscalizations.Core/Model/Countries/Countries.cs

Fixed Spanish tax identifier regex (end/start)

Fixed Spanish tax identifier regex

---

src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
src/Germany/Mews.Fiscalizations.Germany/V2/RequestCreator.cs
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj

Bumped the lib versions to use the latest core lib.

Bumped the lib versions to use latest core.

---

src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Updated Mews.Fiscalizations.All.csproj version

Updated Mews.Fiscalizations.All.csproj version

---

src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Basque/Mews.Fiscalizations.Basque/Model/TicketBaiInvoiceData.cs
src/Basque/Mews.Fiscalizations.Basque/TicketBaiClient.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Extended the TicketBaiInvoiceData so it includes the trimmed signature that is needed later for the request.

Extended the TicketBaiInvoiceData with the trimmed signature.

---

.github/workflows/build-and-test-all.yml
.github/workflows/publish-all-2.yml
.github/workflows/publish-all.yml
.github/workflows/publish-austria.yml
.github/workflows/publish-basque.yml
.github/workflows/publish-core.yml
.github/workflows/publish-czechia.yml
.github/workflows/publish-germany.yml
.github/workflows/publish-hungary.yml
.github/workflows/publish-italy.yml
.github/workflows/publish-spain.yml

Fixed publish GH actions

---

.github/workflows/publish-all.yml
.github/workflows/publish-austria.yml
.github/workflows/publish-basque.yml
.github/workflows/publish-core.yml
.github/workflows/publish-czechia.yml
.github/workflows/publish-germany.yml
.github/workflows/publish-hungary.yml
.github/workflows/publish-italy.yml
.github/workflows/publish-spain.yml
src/Basque/Mews.Fiscalizations.Basque.Tests/InvoiceTestData.cs

Fixed NuGet publish GH actions.
The pipelines are failing due to conflicts.

Fixed NuGet publish GH actions.

---

src/Italy/Mews.Fiscalizations.Italy.Tests/UniwixClientTests.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/DtoUtils.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/Address.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/GeneralDocumentData.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/Identity.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/InvoiceLine.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/PaymentDetail.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/TaxRateSummary.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/TransmissionData.cs
src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Fixed stripping diacritics from IT fiscalization DTOs.

Fixed stripping diacritics from IT fiscalization DTOs

---

src/Basque/Mews.Fiscalizations.Basque.Tests/TestFixture.cs
src/Basque/Mews.Fiscalizations.Basque/Model/ErrorCode.cs
src/Italy/Mews.Fiscalizations.Italy.Tests/UniwixClientTests.cs
src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Italy/Mews.Fiscalizations.Italy/Uniwix/Communication/Dto/ValidationError.cs
src/Italy/Mews.Fiscalizations.Italy/Uniwix/Communication/UniwixClient.cs
src/Italy/Mews.Fiscalizations.Italy/Uniwix/Errors/ErrorResult.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Improved the Italian fiscalization error response DTO.

Improved the Italian fiscalization error response DTO

---

src/Core/Mews.Fiscalizations.Core.Tests/Model/Strings/BasicLatinStringTests.cs
src/Core/Mews.Fiscalizations.Core/Mews.Fiscalizations.Core.csproj
src/Core/Mews.Fiscalizations.Core/Model/Extensions/StringExtensions.cs

Introduced a method that converts a string to Basic Latin standard.

Introduced a method that converts a string to Basic Latin standard.

---

src/Italy/Mews.Fiscalizations.Italy/Dto/DtoUtils.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/Address.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/GeneralDocumentData.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/Identity.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/InvoiceLine.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/PaymentDetail.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/TaxRateSummary.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/TransmissionData.cs
src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Changed all SDI strings to Basic Latin standard

Changed all SDI strings to Basic Latin standard

---

src/Italy/Mews.Fiscalizations.Italy.Tests/UniwixClientTests.cs
src/Italy/Mews.Fiscalizations.Italy/Constants/NormativeReference.cs
src/Italy/Mews.Fiscalizations.Italy/Dto/Invoice/TaxKind.cs
src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

RND-166219 - Updated SDI (IT fiscalzation) tax kinds.

Updated SDI (IT fiscalzation) tax kinds

---

src/Austria/Mews.Fiscalizations.Austria.Tests/Mews.Fiscalizations.Austria.Tests.csproj
src/Austria/Mews.Fiscalizations.Austria/Mews.Fiscalizations.Austria.csproj
src/Basque/Mews.Fiscalizations.Basque.Tests/Mews.Fiscalizations.Basque.Tests.csproj
src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Core/Mews.Fiscalizations.Core.Tests/Mews.Fiscalizations.Core.Tests.csproj
src/Germany/Mews.Fiscalizations.Germany.Tests/Mews.Fiscalizations.Germany.Tests.csproj
src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
src/Hungary/Mews.Fiscalizations.Hungary.Tests/Mews.Fiscalizations.Hungary.Tests.csproj
src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
src/Italy/Mews.Fiscalizations.Italy.Tests/Mews.Fiscalizations.Italy.Tests.csproj
src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain.Tests/Mews.Fiscalizations.Spain.Tests.csproj
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj

Bumped the project's versions, this also updates the NuGet packages to the latest stable version.

Bumped the project's versions

---

src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Mews.Fiscalizations.All.props
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj

Just a bump of funcsharp version.
Fixes #issue

Bumped funcsharp package

---

src/Mews.Fiscalizations.All.props

This makes sure we cannot update to funcsharp 6 that will have some breaking changes.

Make sure we don't break this with a funcsharp update.

---

src/Austria/Mews.Fiscalizations.Austria/Mews.Fiscalizations.Austria.csproj
src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Core/Mews.Fiscalizations.Core/Mews.Fiscalizations.Core.csproj
src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Mews.Fiscalizations.All.props
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj

Bumped versions of all the projects to signal funcsharp dependency version.
Fixes #issue

Bumped versions of all the projects

---

src/Austria/Mews.Fiscalizations.Austria/Mews.Fiscalizations.Austria.csproj
src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Mews.Fiscalizations.All.props
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj

Bumped funcsharp version and returned it to the original naming.
Fixes #issue

Funcsharp bump

---

src/Mews.Fiscalizations.All.props
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Bumped a funcsharp version
Fixes #issue

Bumped funcsharp

---

src/Mews.Fiscalizations.All.props
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Bumped funcsharp version - fixed issue with NonEmptyEnumerable

---

src/Mews.Fiscalizations.All.props
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Finally a non-preview version of FuncSharp.

Funcsharp 7

---

src/Austria/Mews.Fiscalizations.Austria/Mews.Fiscalizations.Austria.csproj
src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Mews.Fiscalizations.All.props
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj

Bumped to funcsharp 7.0.1

---

src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

bumped version of master package.

---

src/Basque/Mews.Fiscalizations.Basque/SigningService.cs
src/Basque/Mews.Fiscalizations.Basque/TicketBaiClient.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

A temporary fix for signing ticketbai xml using XadES-BES

Fixed tbai signature signing

---

src/Mews.Fiscalizations.All.props
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Bumped funcsharp version

---

src/Italy/Mews.Fiscalizations.Italy.Tests/UniwixClientTests.cs
src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Italy/Mews.Fiscalizations.Italy/Uniwix/Communication/UniwixClient.cs
src/Italy/Mews.Fiscalizations.Italy/Uniwix/Errors/ErrorType.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Fixed invoice error handling in the IT fiscalization

Fixed invoice error handling in the IT fiscalization

---

src/Basque/Mews.Fiscalizations.Basque/Dto/Bizkaia/LROERequest.cs

There was a bug in the way DTOS were generated previously. This PR should fix them.
Fixes #issue
- [x ] Bug fix.

Fix LROE request dtos

---

src/Mews.Fiscalizations.All.props
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Just a bump in package version.

Bumped funcsharp to version 8

---

.github/workflows/pr-automation-tech-be-assign.yml
.github/workflows/pr-automation-tech-review-qa-assign.yml
.github/workflows/pr-automation-tech-review-qa-move-on-close.yml
src/Basque/Mews.Fiscalizations.Basque.Tests/Bizkaia/BizkaiaDataValidationTests.cs
src/Basque/Mews.Fiscalizations.Basque/Dto/Bizkaia/Header/BizkaiaHeaderData.cs

Fixed an issue when serializing bizkaia header mode

Fixed an issue when serializing bizkaia header mode

---

src/Basque/Mews.Fiscalizations.Basque.Tests/Bizkaia/BizkaiaDataValidationTests.cs
src/Basque/Mews.Fiscalizations.Basque/Dto/Bizkaia/Header/BizkaiaHeaderData.cs

Avoid writing files in test
Removing extra spaces in Bizkaia Data
Fixes #issue
- [ x] Bug fix.

Fix test output

---

src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Basque/Mews.Fiscalizations.Basque/TicketBaiClient.cs
src/Core/Mews.Fiscalizations.Core/Mews.Fiscalizations.Core.csproj
src/Core/Mews.Fiscalizations.Core/Xml/Signing/Microsoft.Xades/XadesSignedXml.cs
src/Core/Mews.Fiscalizations.Core/Xml/Signing/Signature/Parameters/SignerRole.cs
src/Core/Mews.Fiscalizations.Core/Xml/Signing/XadesService.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Improved the Xades signing so now we validate the signed document after the signing process to make sure all is good

Improved the Xades signing

---

src/Basque/Mews.Fiscalizations.Basque.Tests/TestFixture.cs
src/Basque/Mews.Fiscalizations.Basque/QrCodeUriGenerator.cs
src/Basque/Mews.Fiscalizations.Basque/ServiceInfo.cs

Fixed Bizkaia/TicketBai QR code URI and encoded the query params..
Fixes #issue

Fixed Bizkaia/TicketBai QR code URI and encoded the query params.

---

src/Mews.Fiscalizations.All.props
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Updated funcsharp to the version that specified equality for all the structs.
Fixes #issue

Updated funcsharp again.

---

src/Spain/Mews.Fiscalizations.Spain.Tests/Basics.cs

Un-ignored the Spanish fiscalization tests.

Un-ignored the Spanish fiscalization tests.

---

src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain/Converters/ModelToDtoConverter.cs
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj

Fixed mapping tax summaries to DTO - SII

Fixed mapping tax summaries to DTO - SII

---

src/Austria/Mews.Fiscalizations.Austria/Mews.Fiscalizations.Austria.csproj
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Downgraded System.IdentityModel.Tokens.Jwt to 6.34

Downgraded System.IdentityModel.Tokens.Jwt to 6.34

---

src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain/Mews.Fiscalizations.Spain.csproj
src/Spain/Mews.Fiscalizations.Spain/Model/Request/ForeignCustomer.cs

Relaxed the foreign customer validation - spanish SII

Relaxed the foreign customer validation - spanish SII

---

src/Spain/Mews.Fiscalizations.Spain.Tests/Basics.cs

Minor refactor of the Spanish fiscalization tests + adding some tests to show how Invoices with Zero VAT should be handled in the Spanish fiscalization.
Fixes #issue
- [x ] Tests included (please specify cases).

Refactored Spanish fiscalization tests and added tests to support Zero VAT Invoices

---

src/Austria/Mews.Fiscalizations.Austria/ATrust/ATrustSigner.cs
src/Austria/Mews.Fiscalizations.Austria/Mews.Fiscalizations.Austria.csproj
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Improved Austrian fiscalization response handling.

Improved Austrian fiscalization response handling.

---

src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Result/ErrorResult.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Result/FiskalyError.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Introduced support for the error code from Fiskaly: "E_EXPORT_IN_PROGRESS". This way we can avoid getting errors for this cause in Sentry.  
Fixes #issue
- [x ] Consolidation.

German Fiscalization: Process the error code from Fiskaly "E_EXPORT_IN_PROGRESS"

---

.github/workflows/build-and-test-all.yml
.github/workflows/publish-sweden.yml
README.md
src/Austria/Mews.Fiscalizations.Austria.Tests/Mews.Fiscalizations.Austria.Tests.csproj
src/Basque/Mews.Fiscalizations.Basque.Tests/Mews.Fiscalizations.Basque.Tests.csproj
src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Core/Mews.Fiscalizations.Core.Tests/Mews.Fiscalizations.Core.Tests.csproj
src/Germany/Mews.Fiscalizations.Germany.Tests/Mews.Fiscalizations.Germany.Tests.csproj
src/Hungary/Mews.Fiscalizations.Hungary.Tests/Mews.Fiscalizations.Hungary.Tests.csproj
src/Italy/Mews.Fiscalizations.Italy.Tests/Mews.Fiscalizations.Italy.Tests.csproj
src/Mews.Fiscalizations.All.sln
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Spain/Mews.Fiscalizations.Spain.Tests/Mews.Fiscalizations.Spain.Tests.csproj
src/Sweden/Mews.Fiscalizations.Sweden.Tests/Mews.Fiscalizations.Sweden.Tests.csproj
src/Sweden/Mews.Fiscalizations.Sweden.Tests/Srv4POSTests.cs
src/Sweden/Mews.Fiscalizations.Sweden/DTOs/CheckCashRegisterUniquenessRequest.cs
src/Sweden/Mews.Fiscalizations.Sweden/DTOs/CheckCashRegisterUniquenessResponse.cs
src/Sweden/Mews.Fiscalizations.Sweden/DTOs/CreateActivationRequest.cs
src/Sweden/Mews.Fiscalizations.Sweden/DTOs/CreateActivationResponse.cs
src/Sweden/Mews.Fiscalizations.Sweden/DTOs/SendDataRequest.cs
src/Sweden/Mews.Fiscalizations.Sweden/DTOs/SendDataResponse.cs
src/Sweden/Mews.Fiscalizations.Sweden/DecimalExtensions.cs
src/Sweden/Mews.Fiscalizations.Sweden/Mappers.cs
src/Sweden/Mews.Fiscalizations.Sweden/Mews.Fiscalizations.Sweden.csproj
src/Sweden/Mews.Fiscalizations.Sweden/Models/CreateActivationRequest.cs
src/Sweden/Mews.Fiscalizations.Sweden/Models/CreateActivationResponse.cs
src/Sweden/Mews.Fiscalizations.Sweden/Models/SendDataRequest.cs
src/Sweden/Mews.Fiscalizations.Sweden/Models/SendDataResponse.cs
src/Sweden/Mews.Fiscalizations.Sweden/Srv4posClient.cs
src/Sweden/README.md

Introduced Swedish fiscalization (part 1) - Activation and KD endpoint intorduced.
Fixes #issue

Introduced Swedish fiscalization (part 1) - Activation and KD endpoint intorduced

---

src/Basque/Mews.Fiscalizations.Basque.Tests/TestFixture.cs
src/Basque/Mews.Fiscalizations.Basque/Model/ErrorCode.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Sweden/Mews.Fiscalizations.Sweden/DTOs/Srv4posBasicErrorResponse.cs
src/Sweden/Mews.Fiscalizations.Sweden/DTOs/Srv4posError.cs
src/Sweden/Mews.Fiscalizations.Sweden/Mews.Fiscalizations.Sweden.csproj
src/Sweden/Mews.Fiscalizations.Sweden/Models/ErrorResponse.cs
src/Sweden/Mews.Fiscalizations.Sweden/Models/Srv4posErrorType.cs
src/Sweden/Mews.Fiscalizations.Sweden/Srv4posClient.cs

Added handling of srv4pos error responses.
P.S We know that's not perfect and it doesn't handle all the cases, but it should be good enough for now. We will revisit it in the feature for improvements.

Added handling of srv4pos error responses.

---

src/Basque/Mews.Fiscalizations.Basque.Tests/TestFixture.cs
src/Basque/Mews.Fiscalizations.Basque/DtoToModelConverter.cs
src/Basque/Mews.Fiscalizations.Basque/Mews.Fiscalizations.Basque.csproj
src/Basque/Mews.Fiscalizations.Basque/TicketBaiClient.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Improved xml deserialization error handling in the Basque fiscalization when we receive badly formatted Xml responses from the Basque api.
Fixes #issue
- [x ] Bug fix.

Improved xml deserialization error handling in Basque fiscalization

---

src/Austria/Mews.Fiscalizations.Austria.Tests/ATrustSignerTests.cs
src/Austria/Mews.Fiscalizations.Austria/ATrust/ATrustSigner.cs
src/Austria/Mews.Fiscalizations.Austria/Mews.Fiscalizations.Austria.csproj
src/Basque/Mews.Fiscalizations.Basque/TicketBaiClient.cs
src/Germany/Mews.Fiscalizations.Germany.Tests/V2/FiskalyTestFixture.cs
src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
src/Germany/Mews.Fiscalizations.Germany/V2/Client.cs
src/Germany/Mews.Fiscalizations.Germany/V2/FiskalyClient.cs
src/Hungary/Mews.Fiscalizations.Hungary.Tests/TestFixture.cs
src/Hungary/Mews.Fiscalizations.Hungary/Mews.Fiscalizations.Hungary.csproj
src/Hungary/Mews.Fiscalizations.Hungary/NavClient.cs
src/Hungary/Mews.Fiscalizations.Hungary/Utils/Client.cs
src/Italy/Mews.Fiscalizations.Italy.Tests/UniwixClientTests.cs
src/Italy/Mews.Fiscalizations.Italy/Mews.Fiscalizations.Italy.csproj
src/Italy/Mews.Fiscalizations.Italy/Uniwix/Communication/UniwixClient.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Sweden/Mews.Fiscalizations.Sweden.Tests/Srv4POSTests.cs
src/Sweden/Mews.Fiscalizations.Sweden/Mews.Fiscalizations.Sweden.csproj
src/Sweden/Mews.Fiscalizations.Sweden/Srv4posClient.cs

HttpClient is now provided by the users of the library.

HttpClient is now provided by the users of the library

---

src/Germany/Mews.Fiscalizations.Germany/Mews.Fiscalizations.Germany.csproj
src/Germany/Mews.Fiscalizations.Germany/V2/Client.cs
src/Germany/Mews.Fiscalizations.Germany/V2/Model/Result/ErrorResult.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Improve fiskaly error handling

---

src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Sweden/Mews.Fiscalizations.Sweden.Tests/InfrasecTests.cs
src/Sweden/Mews.Fiscalizations.Sweden/Mappers/EnrollmentMappers.cs
src/Sweden/Mews.Fiscalizations.Sweden/Mews.Fiscalizations.Sweden.csproj
src/Sweden/Mews.Fiscalizations.Sweden/Models/NewEnrollmentResponse.cs
src/Sweden/Mews.Fiscalizations.Sweden/Models/StatusEnrollmentResponse.cs

Add responseReason property to enrollment response models

Add responseReason property to enrollment response models

---

src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Sweden/Mews.Fiscalizations.Sweden/InfrasecClient.cs
src/Sweden/Mews.Fiscalizations.Sweden/Mews.Fiscalizations.Sweden.csproj

Added local certificate selection callback

Added local certificate selection callback

---

src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Sweden/Mews.Fiscalizations.Sweden.Tests/EnrollmentTests.cs
src/Sweden/Mews.Fiscalizations.Sweden/Mappers/EnrollmentMappers.cs
src/Sweden/Mews.Fiscalizations.Sweden/Mews.Fiscalizations.Sweden.csproj
src/Sweden/Mews.Fiscalizations.Sweden/Models/NewEnrollmentData.cs

Add LocalAlias property to enrollment data.

Add LocalAlias property to enrollment data.

---

src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mappers/Management/Organizations/OrganizationMapper.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mews.Fiscalizations.Fiskaly.csproj
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Models/Management/Organizations/ManagedOrganization.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Fix Fiskaly management API null response
Fixes #issue

EXP-2200 - Fix Fiskaly management API null response

---

src/Fiskaly/Mews.Fiscalizations.Fiskaly/DTOs/SignES/Invoices/InvoiceResponse.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mappers/SignES/Invoices/InvoiceMapper.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mews.Fiscalizations.Fiskaly.csproj
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Models/SignES/Invoices/InvoiceResponse.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

EXP-2265 - Fix mappings

---

src/Fiskaly/Mews.Fiscalizations.Fiskaly.Tests/SignES/InvoiceTests.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/APIClients/SignESApiClient.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/DTOs/SignES/Invoices/CorrectingInvoiceRequest.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/DTOs/SignES/Invoices/SimplifiedInvoiceRequest.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mappers/SignES/Invoices/InvoiceMapper.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mews.Fiscalizations.Fiskaly.csproj
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Models/SignES/Invoices/CorrectingInvoice.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Added endpoints for amendment in SignES API.
Fixes #issue

EXP-2305 - Implement Correction methods in Fiskalizations library

---

src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj
src/Sweden/Mews.Fiscalizations.Sweden.Tests/TransactionTests.cs
src/Sweden/Mews.Fiscalizations.Sweden/DTOs/RegisterStatusRequest.cs
src/Sweden/Mews.Fiscalizations.Sweden/InfrasecTransactionClient.cs
src/Sweden/Mews.Fiscalizations.Sweden/Mappers/TransactionMappers.cs
src/Sweden/Mews.Fiscalizations.Sweden/Mews.Fiscalizations.Sweden.csproj
src/Sweden/Mews.Fiscalizations.Sweden/Models/RegisterStatusData.cs
src/Sweden/Mews.Fiscalizations.Sweden/Models/RegisterStatusResponse.cs
src/Sweden/Mews.Fiscalizations.Sweden/Models/TransactionResponse.cs

Added Infrasec RegisterStatus API call

Added Infrasec RegisterStatus API call

---

src/Fiskaly/Mews.Fiscalizations.Fiskaly/DTOs/SignES/Invoices/SimplifiedInvoiceRequest.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mappers/SignES/Invoices/InvoiceMapper.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mews.Fiscalizations.Fiskaly.csproj
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Models/SignES/Invoices/SimplifiedInvoice.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Added series to payload
Fixes #issue

EXP-2355 - Modify fiscalizations lib to add series to Fiskaly request

---

src/Fiskaly/Mews.Fiscalizations.Fiskaly.Tests/SignES/TaxpayerTests.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/APIClients/SignESApiClient.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/DTOs/SignES/Taxpayers/CreateTaxpayerAgreementRequest.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/DTOs/SignES/Taxpayers/SignedTaxpayerAgreementRequest.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/DTOs/SignES/Taxpayers/SignedTaxpayerAgreementResponse.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mappers/SignES/Taxpayers/TaxpayerMapper.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mews.Fiscalizations.Fiskaly.csproj
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Models/SignES/Taxpayers/SignedTaxpayerAgreement.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Models/SignES/Taxpayers/TaxpayerAgreementRepresentative.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

EXP-2393 - Add Generate contract, upload contract and download signed contract endpoints in Fiscalizations library (SignES)

---

src/Fiskaly/Mews.Fiscalizations.Fiskaly.Tests/SignES/OffLineQRCodeTests.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/APIClients/SignESApiClient.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mews.Fiscalizations.Fiskaly.csproj
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Added new function to get QR code content offline

---

src/Fiskaly/Mews.Fiscalizations.Fiskaly.Tests/SignES/InvoiceTests.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mappers/SignES/Invoices/InvoiceMapper.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mews.Fiscalizations.Fiskaly.csproj
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Models/SignES/Invoices/CompleteInvoice.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

EXP-2505 - Fix Complete invoice creation

---

src/Fiskaly/Mews.Fiscalizations.Fiskaly/DTOs/SignES/Taxpayers/Address.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mews.Fiscalizations.Fiskaly.csproj
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

fixed variable name

---

src/Fiskaly/Mews.Fiscalizations.Fiskaly/APIClients/SignESApiClient.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mews.Fiscalizations.Fiskaly.csproj
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Fixed file retrieve API call

---

src/Fiskaly/Mews.Fiscalizations.Fiskaly.Tests/SignES/TaxpayerTests.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/APIClients/SignESApiClient.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mews.Fiscalizations.Fiskaly.csproj
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Added endpoint to retrieve latest signed file

---

src/Fiskaly/Mews.Fiscalizations.Fiskaly.Tests/SignES/InvoiceTests.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/DTOs/SignES/Invoices/SimplifiedInvoiceRequest.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mappers/SignES/Invoices/InvoiceMapper.cs
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Mews.Fiscalizations.Fiskaly.csproj
src/Fiskaly/Mews.Fiscalizations.Fiskaly/Models/SignES/Invoices/SimplifiedInvoice.cs
src/Mews.Fiscalizations.All/Mews.Fiscalizations.All.csproj

Added billing system to fiskaly payload
Fixes #issue

Added billing system to fiskaly payload
